name: AndroidCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests_on_api_29:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'

    - name: run ui tests
      run: ./gradlew :ultron:compileDebugKotlin
